services:
  # Web Application Server (Proxy + Static Files)
  web-app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.web  # Use minimal Dockerfile (no Chrome needed)
    image: devarcscontainerregistry.azurecr.io/openvidu-client-web:v0.0.1
    container_name: robot-audio-recorder-web
    command: ["node", "simple-proxy.js"]
    environment:
      - NODE_ENV=production
      - PORT=8080
      - TARGET_SERVER=https://arcs-openvidu-vm.eastasia.cloudapp.azure.com
      # Proxy configuration
      - PROXY_TIMEOUT=30000
      - PROXY_MAX_REDIRECTS=5
      - PROXY_VERIFY_SSL=true
      #      - DOCKER_ENV=true
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - robot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/local-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Headless Browser (connects to web-app) - Use Alpine for size optimization
  headless-browser:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.alpine  # Use Alpine ONLY for headless browser
    image: devarcscontainerregistry.azurecr.io/openvidu-client-browser:v0.0.1
    container_name: robot-audio-recorder-headless
    # Start as root to set up audio permissions, then switch to target user
    # user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
    group_add:
      - "29"  # Host audio group ID
      - "audio"  # Also add audio group by name
    command: ["/app/setup-audio.sh", "node", "headless-launcher.js"]
    environment:
      # Application configuration
      - WEBSITE_URL=http://web-app:8080
      - ROBOT_ID=robot-001
      - NODE_ENV=production
      - TARGET_SERVER=https://arcs-openvidu-vm.eastasia.cloudapp.azure.com
      
      # Participant configuration
      - PARTICIPANT_NAME_PREFIX=robot-001
      - PARTICIPANT_NAME_SUFFIX_LENGTH=8
      - PARTICIPANT_NAME_GENERATION=timestamp
      
      # Chrome/Puppeteer configuration - using Chromium in Alpine
      - CHROME_BIN=/usr/bin/chromium-browser
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      
      # User switching for audio setup
      - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
      - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      
      # Audio configuration for Ubuntu 18 - USB Audio Device (card 1)
      - ALSA_DEVICE=hw:1,0
      - AUDIO_DEVICE=hw:1,0
      - ALSA_PCM_CARD=1
      - ALSA_PCM_DEVICE=0
      
      # WebRTC and media configuration
      - WEBRTC_ENABLED=true
      - MEDIA_DEVICES_ENABLED=true
      - AUTOPLAY_POLICY=no-user-gesture-required
      
      # Chrome flags for real audio device access (not fake devices)
      - CHROME_ARGS=--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--disable-setuid-sandbox,--disable-web-security,--allow-running-insecure-content,--unsafely-treat-insecure-origin-as-secure,--autoplay-policy=no-user-gesture-required,--hide-scrollbars,--incognito,--use-fake-ui-for-media-stream,--alsa-output-device=hw:1,0,--alsa-input-device=hw:1,0
      
      # Logging and debugging
      - ENABLE_LOGGING=true
      - LOG_LEVEL=info
      - DEBUG=false
      
      # Connection settings
      - KEEP_ALIVE=true
      - RECONNECT_DELAY=30000
      - MAX_RECONNECT_ATTEMPTS=3
      - CONNECTION_TIMEOUT=60000
      
      # Performance settings
      - MAX_MEMORY=2048
      - SHARED_MEMORY_SIZE=2gb
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      # Audio device access for Ubuntu 18 - with proper permissions
      - /dev/snd:/dev/snd:rw
      - /sys/class/sound:/sys/class/sound:ro
      # Mount host audio configuration
      - /etc/asound.conf:/etc/asound.conf:ro
    tmpfs:
      - /app/.config/chromium:uid=1000,gid=1000,mode=755
      - /app/.cache:uid=1000,gid=1000,mode=755
    restart: unless-stopped
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_NICE  # For audio priority
      - DAC_OVERRIDE  # Override file permissions for audio devices
      - CHOWN  # Allow changing ownership
      - FOWNER  # Allow file operations
    privileged: true  # Enable full access for audio device setup
    devices:
      - /dev/snd:/dev/snd  # Audio devices
    depends_on:
      web-app:
        condition: service_healthy
    restart: unless-stopped
    init: true  # Ensures proper PID 1 handling for audio processes
    networks:
      - robot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web-app:8080/local-health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  robot-network:
    driver: bridge

volumes:
  logs:
    driver: local
